language: c
cache: ccache
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILDDIR=. TOOL="./configure"
    - os: linux
      compiler: gcc
      env: BUILDDIR=. TOOL="./configure --zlib-compat --native"
    - os: linux
      compiler: gcc
      env: BUILDDIR=../build TOOL="../zlib-ng/configure --zlib-compat"
    - os: linux
      compiler: gcc
      env: BUILDDIR=. TOOL="./configure --zlib-compat --without-optimizations --without-new-strategies"
    - os: linux
      compiler: gcc
      env: BUILDDIR=. TOOL="./configure --32"
      install:
      - sudo apt-get update
      - sudo apt-get install gcc-multilib
    - os: linux
      compiler: gcc
      env: BUILDDIR=. TOOL="cmake ."
    - os: linux
      compiler: gcc
      env: BUILDDIR=../build TOOL="cmake ../zlib-ng"

    - os: linux
      compiler: clang
      env: BUILDDIR=. TOOL="./configure --zlib-compat"
    - os: linux
      compiler: clang
      env: BUILDDIR=../build TOOL="cmake ../zlib-ng"

    - os: osx
      compiler: gcc
      env: BUILDDIR=. TOOL="./configure --zlib-compat"
    - os: osx
      compiler: gcc
      env: BUILDDIR=../build TOOL="../zlib-ng/configure --zlib-compat"
    - os: osx
      compiler: gcc
      env: BUILDDIR=. TOOL="cmake ."

    - os: osx
      compiler: clang
      env: BUILDDIR=. TOOL="./configure --zlib-compat"
    - os: osx
      compiler: clang
      env: BUILDDIR=../build TOOL="cmake ../zlib-ng"

script: mkdir -p $BUILDDIR && cd $BUILDDIR && $TOOL && make -j2 && make test
