language: c
compiler:
  - gcc
  - clang
env:
  - BUILDDIR=. TOOL="./configure"
  - BUILDDIR=. TOOL="./configure --native"
  - BUILDDIR=. TOOL="./configure --zlib-compat"
  - BUILDDIR=. TOOL="./configure --zlib-compat --without-optimizations --without-new-strategies"
  - BUILDDIR=../build TOOL="../zlib-ng/configure"
  - BUILDDIR=. TOOL="cmake ."
  - BUILDDIR=. TOOL="cmake -DWITH_NATIVE_INSTRUCTIONS=on ."
  - BUILDDIR=. TOOL="cmake -DZLIB_COMPAT=on ."
  - BUILDDIR=. TOOL="cmake -DZLIB_COMPAT=on -DWITH_OPTIM=off -DWITH_NEW_STRATEGIES=off ."
  - BUILDDIR=../build TOOL="cmake ../zlib-ng"
script: mkdir -p $BUILDDIR && cd $BUILDDIR &&
        $TOOL && make && make test
